//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ogrenciler
    {
        public int ogr_id { get; set; }

        [Display(Name ="Öðrenci Ýsmi")]
        [Required(ErrorMessage ="Öðrenci Ýsmi Boþ Býrakýlamaz!")]
        public string ogr_isim { get; set; }

        [Display(Name = "Öðrenci Soyismi")]
        [Required(ErrorMessage = "Öðrenci Soyismi Boþ Býrakýlamaz!")]
        public string ogr_soyisim { get; set; }

        [Display(Name = "Öðrenci Yaþ")]
        [Range(10, 100, ErrorMessage = "Öðrencinin yaþý 10-100 arasýnda olmalýdýr.")]
        [Required(ErrorMessage ="Öðrenci yaþý boþ býrakýlamaz.")]
        public int ogr_yas { get; set; }

        [Display(Name = "Öðrenci Doðum Tarihi")]
        [Required(ErrorMessage = "Öðrenci Doðum Tarihi Boþ Býrakýlamaz!")]
        public System.DateTime ogr_dogumtarih { get; set; }
    }
}
